name: Pipeline CI - Niveau 2


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    - name: Vérifier la présence des fichiers
      run: |
        test -f index.html || (echo "Erreur: index.html manquant" && exit 1)
        test -f nginx.conf || (echo "Erreur: nginx.conf manquant" && exit 1)
        test -f dockerfile || (echo "Erreur: Dockerfile manquant" && exit 1)

    - name: Build de l'image Docker
      run: docker build -t mon-nginx-test .

    - name: Tester la configuration Nginx
      run: docker run --rm mon-nginx-test nginx -t

    - name: Lancer le conteneur de test
      run: |
        docker run -d -p 8080:80 --name serveur-test mon-nginx-test
        sleep 3

    - name: Tester la réponse HTTP (Page d'accueil)
      run: |
        curl -s --fail http://localhost:8080/ | grep "Mon TP CI/CD" || (echo "Erreur: Le service ne répond pas correctement" && exit 1)

    - name: Tester l'endpoint /health
      run: |
        REPONSE=$(curl -s http://localhost:8080/health)
        if [ "$REPONSE" != "OK" ]; then
          echo "Erreur: L'endpoint /health a renvoyé '$REPONSE' au lieu de 'OK'"
          exit 1
        fi
        echo "L'endpoint /health fonctionne !"

    - name: Arrêter le conteneur de test
      if: always()
      run: docker rm -f serveur-test